import axios from 'axios';
import produce from 'immer';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { useRecoilState } from 'recoil';
import slugify from 'slugify';
import dbConnect from '../lib/dbConnect';
import course from '../models/course';
import { courseBuildAtom } from '../recoil/atoms/courseBuildAtom';
import { CourseType, CourseName } from '../types';
import { useSession, signIn, signOut, getSession } from 'next-auth/react';
import user from '../models/user';

const Home: React.FC<{ courses: CourseName[] }> = ({ courses }) => {
  const [courseTitle, setCourseTitle] = useState<string>('');
  const [pulledCourses, setPulledCourses] = useState<CourseName[]>(courses);
  const [courseInfo, setCourseInfo] = useRecoilState<CourseType>(courseBuildAtom);
  const router = useRouter();
  const { data: session } = useSession();

  useEffect(() => {
    axios.get('/api/user/getId').then((message) => console.log(message));
  }, []);

  const createCourse = () => {
    if (!courseTitle) {
      return;
    }
    const slug = slugify(courseTitle, { lower: true });
    const setSlug = produce(courseInfo, (draft) => {
      draft.slug = slug;
      draft.courseName = courseTitle;
    });
    setCourseInfo(setSlug);
    router.push(`/builder/${slug}`);
  };

  const deleteBySlug = (slug: string): void => {
    axios.delete(`/api/courseBuilder/${slug}`).then((response) => {
      if (response.data.success) {
        const index = pulledCourses.findIndex((item) => item.slug === slug);
        const removeItem = produce(pulledCourses, (draft) => {
          draft = draft.splice(index, 1);
        });
        setPulledCourses(removeItem);
      }
    });
  };

  return (
    <div className="w-full screen-h">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {session ? (
          <button onClick={() => signOut()}>Sign out</button>
        ) : (
          <button onClick={() => signIn()}>Sign in</button>
        )}
        <input
          type="text"
          className="p-3 border outline-none"
          value={courseTitle}
          onChange={(e) => setCourseTitle(e.target.value)}
        />
        <button className="p-3 mb-3 border" onClick={createCourse}>
          Create course
        </button>
        {pulledCourses.map((item, key) => (
          <div className="flex space-x-2" key={key}>
            <p>
              {item.courseName} {item.slug}
            </p>
            <button className="border" onClick={() => deleteBySlug(item.slug)}>
              Delete
            </button>
            <Link href={`/builder/${item.slug}`}>
              <a className="p-3 border">Edit course</a>
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
};
export default Home;

export async function getServerSideProps(context) {
  // const sess = await getSession(context);
  await dbConnect();
  // const getId = await user.findOne({ email: sess.user.email });
  // console.log(getId);

  const courses: CourseName[] = await course.find().select('slug courseName');
  return {
    props: {
      courses: JSON.parse(JSON.stringify(courses)),
    },
  };
}
