import Head from 'next/head';
import Button from '@material-tailwind/react/Button';
import { modalCourseNameAtom } from '../recoil/atoms/modalsAtom';
import { useRecoilState } from 'recoil';
import ModalCourseName from '../components/ModalCourseName';
import Accordion from '../components/Accordion';

export default function Home() {
  const [showModal, setShowModal] = useRecoilState(modalCourseNameAtom);

  const toggleModal = (e) => {
    e.preventDefault();
    let toggle = { ...showModal };
    toggle.isOpen = true;
    setShowModal(toggle);
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Button color="lightBlue" type="button" onClick={toggleModal} ripple="light">
          Open small Modal
        </Button>
        <ModalCourseName />
      </div>
      <div>
        <Accordion />
      </div>
    </div>
  );
}
